### ISSUE TITLE
Failed to parse URI options: Default authentication mechanism requires username.

### ISSUE THREAD

**Issue by starred-gijs** [facile-it/mongodb-bundle#96]
When I use a docker container without auth, the connection fails, with this exception:
 `Failed to parse URI options: Default authentication mechanism requires username.`

My config
```yaml
mongo_db_bundle:
    data_collection: '%kernel.debug%'
    clients:
        default:
            uri: 'mongodb://mongo:27017'
    connections:
        default:
            client_name:    default
            database_name:  'database_name'
```

I think its related to https://github.com/facile-it/mongodb-bundle/blob/2ffbb5bbb335c64a327c971e13ab0d9519da4c10/src/Services/ClientRegistry.php#L155-L161

Where the `$conf->getOptions()` does not contain 'authSource' value (empties are filtered out), the options array becomes

```
array:4 [▼
  "database" => "database_name"
  "authSource" => "database_name"
  "ssl" => false
  "readPreference" => "primaryPreferred"
]
```

When I manually drop the authSource, its works perfectly. What can I do to fix this?

**Comment by Jean85** [comment]
Adding a regression test into https://github.com/facile-it/mongodb-bundle/blob/master/tests/Unit/DependencyInjection/ConfigurationTest.php would probably help. PR welcome!

**Comment by starred-gijs** [comment]
I had a look al the test you mentioned, but that part is not broken. The issue is that you can't unset the 'authSource' option, see the code snippet above. The `$conf->getOptions()` is cleaned from empty values, stripping the authSource, hence it uses the value from the first array, ` 'authSource' => $conf->getAuthSource() ?? $databaseName ?? 'admin'`

I tried to add a failing test to ClientRegistryTest, but did not figure out how to check the $uriOptions from the Client class...

**Comment by soldierdi** [comment]
Hello,
I had the same problem because I wanted to access a mongodb database without credentials. For the time being I'm using 
```yaml
mongo_db_bundle:
    data_collection: '%kernel.debug%'
    clients:
        default:
            uri: 'mongodb://mongo:27017'
            authSource: '$external'
  
    connections:
        default:
            client_name:    default
            database_name:  '%env(MONGO_INITDB_DATABASE)%'
```
The value *$external* for "authSource" should be used for [external authentication mechanisms](https://www.php.net/manual/en/mongodb-driver-manager.construct.php) but it also works for me while accessing a mongodb instance in a docker container that has no credentials for authentication set. I hope this helps.
